-- SEED module Audits de conformité (généré par audit_seed.py) — questions VERBATIM de l'Excel.

insert into public.audit_grille (id,titre,cible,referentiel,version,active) values ($$GRL-FLASH$$,$$Audit flash de poste (T1-T9)$$,$$poste$$,$$combine$$,1,true) on conflict (id) do nothing;
insert into public.audit_grille (id,titre,cible,referentiel,version,active) values ($$GRL-CF$$,$$Grille contrôle final & libération$$,$$poste$$,$$combine$$,1,true) on conflict (id) do nothing;
insert into public.audit_grille (id,titre,cible,referentiel,version,active) values ($$GRL-SOU$$,$$Grille soudure (procédé spécial)$$,$$procede$$,$$combine$$,1,true) on conflict (id) do nothing;
insert into public.audit_grille (id,titre,cible,referentiel,version,active) values ($$GRL-EMB$$,$$Grille emballage$$,$$poste$$,$$combine$$,1,true) on conflict (id) do nothing;
insert into public.audit_grille (id,titre,cible,referentiel,version,active) values ($$GRL-INFO$$,$$Grille informatique (27001/RGPD)$$,$$process$$,$$27001$$,1,true) on conflict (id) do nothing;

delete from public.audit_question where grille_id in ($$GRL-FLASH$$,$$GRL-CF$$,$$GRL-SOU$$,$$GRL-EMB$$,$$GRL-INFO$$);

insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-01$$,$$GRL-FLASH$$,1,$$T1$$,$$T1$$,$$EN 9100 §8.5.1.a$$,$$Fiche d'instruction + fiche suiveuse présentes et au bon indice ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-02$$,$$GRL-FLASH$$,2,$$T2$$,$$T2$$,$$EN 9100 §8.5.2/8.6$$,$$Mesures d'autocontrôle enregistrées, traçabilité lot et matière, tampon/matricule GPAO ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-03$$,$$GRL-FLASH$$,3,$$T3$$,$$T3$$,$$EN 9100 §7.1.5$$,$$Les ECME utilisés au poste sont-ils dans leur validité d'étalonnage ?$$,NULL,$$auto$$,$$ecme$$) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-04$$,$$GRL-FLASH$$,4,$$T4$$,$$T4$$,$$EN 9100 §7.1.4$$,$$Poste propre, rangé, sans FOD ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-05$$,$$GRL-FLASH$$,5,$$T5$$,$$T5$$,$$ISO 45001 §8$$,$$Port des EPI obligatoires et respect des consignes ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-06$$,$$GRL-FLASH$$,6,$$T6$$,$$T6$$,$$EN 9100 §7.1.3$$,$$Maintenance 1er niveau réalisée ; VGP des équipements à jour ?$$,NULL,$$auto$$,$$vgp$$) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-07$$,$$GRL-FLASH$$,7,$$T7$$,$$T7$$,$$ISO 45001 §6.1.2$$,$$L'opérateur connaît-il les risques de son poste et le moyen de remonter une situation dangereuse ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-08$$,$$GRL-FLASH$$,8,$$T8$$,$$T8$$,$$ISO 45001 §8.1.2$$,$$Consignation LOTO / permis de travail respectés (permis feu, plan de prévention) ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-FLASH-09$$,$$GRL-FLASH$$,9,$$T9$$,$$T9$$,$$Code du travail R.4412$$,$$Risques bruit/CMR maîtrisés ; FDS présentes, captage à la source en service ?$$,NULL,$$auto$$,$$fds$$) on conflict (id) do nothing;

insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-01$$,$$GRL-CF$$,1,$$Q 1.1$$,$$T1$$,$$EN 9100 §8.5.1.1$$,$$le salarié dispose-t-il du dossier de fabrication complet (fiche suiveuse, plan, gamme)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-02$$,$$GRL-CF$$,2,$$Q 1.2$$,$$T1$$,$$EN 9100 §8.5.1.1$$,$$l'indice de révision du plan utilisé au contrôle correspond-il exactement à la dernière version informatique?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-03$$,$$GRL-CF$$,3,$$Q 2.1$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$toutes les étapes de fabrication précédentes ont-elles bien été signées sur la fiche suiveuse avant le contrôle final?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-04$$,$$GRL-CF$$,4,$$Q 2.2$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$comment le salarié matérialise-t-il l'acceptation finale du lot (tampon, signature, GPAO)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-05$$,$$GRL-CF$$,5,$$Q 2.3$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$si une pièce est non-conforme, comment est-elle gérée pour éviter tout mélange avec les pièces conformes?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-06$$,$$GRL-CF$$,6,$$Q 2.4$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le salarié utilise-t-il le plan de contrôle pour guider ses vérifications? Le cas échéant, le nombre de pièces effectivement contrôlées est-il strictement conforme à la taille d'échantillon ou à la fréquence exigée par le plan de contrôle (ex: 100% des pièces, table ISO...)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-07$$,$$GRL-CF$$,7,$$Q 2.5$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le lot en cours est-il soumis à une obligation de Premier Article (FAI) ? (Vérifier si : 1ère production, nouvel indice BEI, ou exigence contractuelle spécifiée sur la commande). Si le rapport FAI a-t-il été dument complété, vérifié et validé (interne ou client) avant d'autoriser la libération du reste du lot ?$$,NULL,$$auto$$,$$fai$$) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-08$$,$$GRL-CF$$,8,$$Q 3.1$$,$$T3$$,$$EN 9100 §7.1.5$$,$$comment le salarié connait-il les équipements de contrôle, de mesure et d'essai (ECME) à utiliser? Les outils utilisés pour le contrôle possèdent-ils tous une vignette d'étalonnage valide (non périmée)?$$,NULL,$$auto$$,$$ecme$$) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-09$$,$$GRL-CF$$,9,$$Q 3.2$$,$$T3$$,$$EN 9100 §7.1.5$$,$$les gabarits ou outils de contrôle spécifiques à cet AR ont-ils bien été contrôlés, rangés au bon endroit, référencé dans le fichier Excel et identifié avant le début du contrôle?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-10$$,$$GRL-CF$$,10,$$Q 4.1$$,$$T4$$,$$EN 9100 §7.1.4$$,$$la table de travail est-elle propre, rangée et exempts d'objets n'appartenant pas à la production en cours (risque FOD/pollution)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-11$$,$$GRL-CF$$,11,$$Q 4.2$$,$$T4$$,$$EN 9100 §7.1.4$$,$$les pièces acceptées sont-elles correctement protégées (bacs, intercalaires) pour éviter des chocs ou des rayures après le contrôle?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-12$$,$$GRL-CF$$,12,$$Q 5.1$$,$$T5$$,$$ISO 45001 §8$$,$$le contrôleur porte-t-il ses équipements de protection individuelle obligatoires dans cette zone?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-CF-13$$,$$GRL-CF$$,13,$$Q 6.1$$,$$T6$$,$$EN 9100 §7.1.3$$,$$l'éclairage du poste est-il suffisant et conforme pour permettre une détection visuelle correcte des défauts d'aspect?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;

insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-01$$,$$GRL-SOU$$,1,$$Q 1.1$$,$$T1$$,$$EN 9100 §8.5.1.1$$,$$le soudeur dispose-t-il du dossier de fabrication complet (fiche suiveuse, plan, gamme) et de la DMOS (Descriptif du Mode Opératoire de Soudage) applicable à la pièce?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-02$$,$$GRL-SOU$$,2,$$Q 1.2$$,$$T1$$,$$EN 9100 §8.5.1.1$$,$$les fiches de données de sécurité (FDS) des produits d'apport (fils, baguettes) ou des gaz sont-elles accessibles au poste?$$,NULL,$$auto$$,$$fds$$) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-03$$,$$GRL-SOU$$,3,$$Q 2.1$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le soudeur possède-t-il sa QS (qualification de soudeur) formelle, nominative et en cours de validité pour le procédé et le matériau utilisés?$$,NULL,$$auto$$,$$certifications$$) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-04$$,$$GRL-SOU$$,4,$$Q 2.2$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le numéro de lot du métal d'apport et le type de gaz utilisé sont-ils correctement relevés pour garantir la traçabilité?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-05$$,$$GRL-SOU$$,5,$$Q 2.3$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le soudeur utilise-t-il le plan de contrôle pour guider ses vérifications?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-06$$,$$GRL-SOU$$,6,$$Q 2.4$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le nombre de pièces inspectées par le soudeur correspond-il strictement aux exigences définies dans ce plan de contrôle?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-07$$,$$GRL-SOU$$,7,$$Q 2.5$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le soudeur atteste-t-il formellement la réalisation de son travail en apposant son matricule sur la fiche suiveuse et dans la GPAO?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-08$$,$$GRL-SOU$$,8,$$Q 3.1$$,$$T3$$,$$EN 9100 §7.1.5$$,$$les indicateurs de gaz intégrés au poste possèdent-ils une vignette de contrôle valide?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-09$$,$$GRL-SOU$$,9,$$Q 3.2$$,$$T3$$,$$EN 9100 §7.1.5$$,$$les paramètres de soudage réels (intensité, tension, débit de gaz) correspondent-ils strictement aux plages définies par la DMOS?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-10$$,$$GRL-SOU$$,10,$$Q 4.1$$,$$T4$$,$$EN 9100 §7.1.4$$,$$le poste de travail est-il propre et exempts d'objets n'appartenant pas à la production en cours (risque FOD/pollution)$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-11$$,$$GRL-SOU$$,11,$$Q 5.1$$,$$T5$$,$$ISO 45001 §8$$,$$le système d'aspiration des fumées de soudage au poste est-il actif, fonctionnel et correctement positionné par l'opérateur?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-12$$,$$GRL-SOU$$,12,$$Q 5.2$$,$$T5$$,$$ISO 45001 §8$$,$$le soudeur porte-t-il ses équipements de protection individuelle obligatoires dans cette zone?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-SOU-13$$,$$GRL-SOU$$,13,$$Q 6.1$$,$$T6$$,$$EN 9100 §7.1.3$$,$$l'état général de la torche, de la pince de masse et des câbles électriques ne présente-t-il aucune usure ou dégradation visible?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;

insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-01$$,$$GRL-EMB$$,1,$$Q 1.1$$,$$T1$$,$$EN 9100 §8.5.1.1$$,$$l'opérateur dispose-t-il de la fiche d'emballage générale et le cas échéant de la fiche d'instruction d'emballage spécifique demandée par le client?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-02$$,$$GRL-EMB$$,2,$$Q 2.1$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$quelles sont les conditions préalables à vérifier avant de pouvoir emballer les pièces (réponse attendue: contrôle final et pointages précédents)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-03$$,$$GRL-EMB$$,3,$$Q 2.2$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$l'opérateur réalise-t-il une ultime vérification visuelle des pièces (absence de chocs visibles, poussière, limaille, tâche d'huile…) avant mise en carton?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-04$$,$$GRL-EMB$$,4,$$Q 2.3$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$l'opérateur atteste-t-il formellement la réalisation de son travail en apposant son matricule sur la fiche suiveuse et dans la GPAO?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-05$$,$$GRL-EMB$$,5,$$Q 2.4$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$si une pièce est non-conforme, comment est-elle gérée pour éviter tout mélange avec les pièces conformes?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-06$$,$$GRL-EMB$$,6,$$Q 2.5$$,$$T2$$,$$EN 9100 §8.5.2 / §8.6$$,$$le salarié utilise-t-il le plan de contrôle pour guider ses vérifications? Le cas échéant, le nombre de pièces effectivement contrôlées est-il strictement conforme à la taille d'échantillon ou à la fréquence exigée par le plan de contrôle (ex: 100% des pièces, table ISO...)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-07$$,$$GRL-EMB$$,7,$$Q 4.1$$,$$T4$$,$$EN 9100 §7.1.4$$,$$le poste de travail est-il propre et exempts d'objets n'appartenant pas à la production en cours (risque FOD/pollution)$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-08$$,$$GRL-EMB$$,8,$$Q 4.2$$,$$T4$$,$$EN 9100 §7.1.4$$,$$les consommables d'emballage (films plastiques, mousses de calage, cartons, papier bulle) sont-ils stockés à l'abri de la poussière et de l'humidité pour éviter de polluer les pièces ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-09$$,$$GRL-EMB$$,9,$$Q 4.3$$,$$T4$$,$$EN 9100 §7.1.4$$,$$les intercalaires ou protections spécifiques sont-ils correctement positionnés entre les pièces pour exclure tout risque de frottement ou de choc pendant le transport?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-10$$,$$GRL-EMB$$,10,$$Q 5.1$$,$$T5$$,$$ISO 45001 §8$$,$$l'opérateur utilise-t-il les aides à la manutention disponible pour le levage des colis lourds afin d'éviter les risques de chutes de matériel ou de blessure?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-11$$,$$GRL-EMB$$,11,$$Q 5.2$$,$$T5$$,$$ISO 45001 §8$$,$$les outils de coupe (cutters) utilisés sont-ils conformes et en bon état?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-EMB-12$$,$$GRL-EMB$$,12,$$Q 6.1$$,$$T6$$,$$EN 9100 §7.1.3$$,$$les équipements de fermeture (cercleuse, filmeuse par exemple) sont-ils propres, fonctionnels et entretenus selon les règles?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;

insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-01$$,$$GRL-INFO$$,1,$$Q B.1$$,$$B$$,$$ISO/IEC 27001 §6.1$$,$$quelle est la stratégie de l'entreprise concernant la gestion des risques cyber pouvant paralyser l'usine? Existe-t-il une cartographie des risques informatiques à jour?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-02$$,$$GRL-INFO$$,2,$$Q B.2$$,$$B$$,$$ISO/IEC 27001 §6.1$$,$$existe-t-il un plan de continuité d'activité (PCA) ou un plan de secours informatique (PSI) formalisé pour assurer le redémarrage de l'usine en cas de sinistre majeur?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-03$$,$$GRL-INFO$$,3,$$Q B.3$$,$$B$$,$$ISO/IEC 27001 §6.1$$,$$existe-t-il une procédure écrite décrivant la fréquence, la méthode et la responsabilité des sauvegardes des données?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-04$$,$$GRL-INFO$$,4,$$Q B.4$$,$$B$$,$$ISO/IEC 27001 §6.1$$,$$le serveur "en miroir" est-il encadré par un protocole informatique sécurisé (VPN, chiffrement) garantissant la non-divulgation des données?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-05$$,$$GRL-INFO$$,5,$$Q B.5$$,$$B$$,$$ISO/IEC 27001 §6.1$$,$$comment s'assure-t-on de la protection et de la confidentialité des données personnelles (RGPD) stockés sur le serveur?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-06$$,$$GRL-INFO$$,6,$$Q B.6$$,$$B$$,$$ISO/IEC 27001 §6.1$$,$$dispose-t-on d'un document clarifiant les rôles de chacun dans la répartition des différents contrats informatiques et téléphonie?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-07$$,$$GRL-INFO$$,7,$$Q C.1$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$quelle est la politique de sauvegarde des données critiques de l'usine (données du B.E.I, historique qualité…)? Les tests de restauration des sauvegardes sont-ils planifiés et réalisés pour prouver que les données sont réellement récupérables? (demander à voir le dernier PV de test de restauration)$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-08$$,$$GRL-INFO$$,8,$$Q C.2$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$où est situé physiquement le serveur de l'entreprise? Son accès est-il restreint, verrouillé et protégé contre l'instrusion ou l'incendie?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-09$$,$$GRL-INFO$$,9,$$Q C.3$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$comment est protégé le serveur contre les coupures de courant ou les surtensions (présence d'un onduleur, d'une batterie de secours testée)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-10$$,$$GRL-INFO$$,10,$$Q C.4$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$comment s'assure-t-on que le personnel (bureaux et atelier) est sensibilisé aux risques informatiques (phishing, choix des mots de passe, fuite d'informations techniques)? Existe-t-il une charte informatique signée par les salariés?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-11$$,$$GRL-INFO$$,11,$$Q C.5$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$qui détient les codes "administrateur" du réseau et des serveurs actuels? Existe-t-il un registre des mots de passe sécurisé en cas de départ d'un collaborateur?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-12$$,$$GRL-INFO$$,12,$$Q C.6$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$les utilisateurs possèdent-ils des identifiants et des mots de passe individuels, robustes et renouvelé régulièrement?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-13$$,$$GRL-INFO$$,13,$$Q C.7$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$l'intégralité du parc de PC (bureaux et atelier) est-elle couverte par un antivirus professionnel géré de manière centralisée?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-14$$,$$GRL-INFO$$,14,$$Q C.8$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$existe-t-il une règle de nommage et d'arborescence pour éviter la prolifération des fichiers en doublons?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-15$$,$$GRL-INFO$$,15,$$Q C.9$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$dispose-t-on d'un listing/inventaire à jour de tous les PC de l'entreprise incluant leur date de mise en service et l'état de leurs licences logicielles?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-16$$,$$GRL-INFO$$,16,$$Q C.10$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$les logiciels installés et utilisés au quotidien sont-ils tous officiellement sous licence valide (absence de logiciels piratés ou crackés)?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-17$$,$$GRL-INFO$$,17,$$Q C.11$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$lors de la remise d'un PC ou d'un téléphone à un collaborateur, un document formel d'attribution (charte de prêt) est-il signé pour garantir la restitution obligatoire du matériel et des données lors de son départ?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-18$$,$$GRL-INFO$$,18,$$Q C.12$$,$$C$$,$$ISO/IEC 27001 §7 / Annexe A$$,$$quelle est la règle de nettoyage des dossiers temporaires (dossier Scan par exemple), des répertoires communs…?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-19$$,$$GRL-INFO$$,19,$$Q H.1$$,$$H$$,$$EN 9100 §9 / §10$$,$$quels sont les indicateurs de performance utilisés pour piloter le processus informatique? Sont-ils à jour et analysés?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;
insert into public.audit_question (id,grille_id,ordre,section,theme_code,clause_ref,libelle,preuve_attendue,mode,sonde) values ($$AQ-INFO-20$$,$$GRL-INFO$$,20,$$Q H2$$,$$H$$,$$EN 9100 §9 / §10$$,$$en cas de panne matérielle ou logicielle impactant la production, comment l'incident est-il enregistré, traité et analysé pour éviter qu'il ne se reproduise?$$,NULL,$$manuel$$,NULL) on conflict (id) do nothing;

insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P01$$,2026,'process',$$Direction$$,$$PILOTAGE$$,$$Usine$$,$$A,H$$,$$H,C$$,$$9001,9100,45001,14001$$,$$2026-12-01$$,60,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P02$$,2026,'process',$$Management QSE$$,$$PILOTAGE$$,$$Usine$$,$$H,I,J,K$$,$$A,B,C,D,E,F,G,H$$,$$9001,9100,45001,14001,27001$$,$$2026-12-01$$,90,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P03$$,2026,'process',$$Commerce$$,$$REALISATION$$,$$Usine$$,$$D$$,$$B,A$$,$$9001,9100$$,$$2026-09-01$$,60,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P04$$,2026,'process',$$B.E.I$$,$$REALISATION$$,$$Usine$$,$$E$$,$$A,B,C$$,$$9001,9100$$,$$2026-11-01$$,120,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P05$$,2026,'process',$$Production$$,$$REALISATION$$,$$Usine$$,$$G,I,J$$,$$A,B,C,H$$,$$9001,9100,45001,14001$$,$$2026-10-01$$,180,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P06$$,2026,'process',$$Logistique$$,$$REALISATION$$,$$Usine$$,$$G,F$$,$$A,B,C$$,$$9001,9100$$,$$2026-11-01$$,90,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P07$$,2026,'process',$$Achats$$,$$SUPPORT$$,$$Usine$$,$$F$$,$$B,A$$,$$9001,9100$$,$$2026-09-01$$,90,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P08$$,2026,'process',$$Administratif/RH$$,$$SUPPORT$$,$$Usine$$,$$C,I$$,$$A$$,$$9001,9100,45001$$,$$2026-10-01$$,90,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,famille,perimetre,themes,themes_transverses,referentiels,date_cible,temps_estime_min,statut) values ($$PRG-2026-P09$$,2026,'process',$$Informatique$$,$$SUPPORT$$,$$Usine$$,$$C,K$$,$$B,H$$,$$9001,9100,27001$$,$$2026-07-01$$,60,'planifie') on conflict (id) do nothing;

insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T01$$,2026,'poste',$$Sertissage$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6$$,$$9001,9100,45001$$,$$2026-06-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T02$$,2026,'poste',$$Poinconnage$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6,T9$$,$$9001,9100,45001$$,$$2026-07-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T03$$,2026,'poste',$$Controle final$$,$$Usine$$,$$T1,T2,T3,T4,T5$$,$$9001,9100,45001$$,$$2026-07-01$$,30,$$GRL-CF$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T04$$,2026,'poste',$$Soudure$$,$$Usine$$,$$T1,T2,T3,T5,T6,T7,T8,T9$$,$$9001,9100,45001$$,$$2026-09-01$$,30,$$GRL-SOU$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T05$$,2026,'poste',$$Emballage$$,$$Usine$$,$$T1,T2,T4,T5$$,$$9001,9100,45001$$,$$2026-09-01$$,30,$$GRL-EMB$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T06$$,2026,'poste',$$Usinage$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6,T9$$,$$9001,9100,45001$$,$$2026-10-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T07$$,2026,'poste',$$Pliage$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6$$,$$9001,9100,45001$$,$$2026-10-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T08$$,2026,'poste',$$Reception magasin$$,$$Usine$$,$$T1,T2,T3,T4,T5$$,$$9001,9100,45001$$,$$2026-11-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T09$$,2026,'poste',$$Troneconnage$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6,T9$$,$$9001,9100,45001$$,$$2026-11-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T10$$,2026,'poste',$$Traitement de surface (Surtec 650)$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6,T9$$,$$9001,9100,45001$$,$$2026-12-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T11$$,2026,'poste',$$Montage$$,$$Usine$$,$$T1,T2,T3,T4,T5$$,$$9001,9100,45001$$,$$2026-12-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T12$$,2026,'poste',$$Serigraphie$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6$$,$$9001,9100,45001$$,$$2027-01-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T13$$,2026,'poste',$$Finitions$$,$$Usine$$,$$T1,T2,T3,T4,T5,T6$$,$$9001,9100,45001$$,$$2027-01-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T14$$,2026,'poste',$$Expedition$$,$$Usine$$,$$T1,T2,T4,T5$$,$$9001,9100,45001$$,$$2027-02-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;
insert into public.audit_programme (id,exercice,type,entite_auditee,perimetre,themes,referentiels,date_cible,temps_estime_min,grille_id,statut) values ($$PRG-2026-T15$$,2026,'poste',$$Maintenance$$,$$Usine$$,$$T3,T4,T5,T6,T8$$,$$9001,9100,45001$$,$$2027-03-01$$,30,$$GRL-FLASH$$,'planifie') on conflict (id) do nothing;

notify pgrst, 'reload schema';
